version: '3.4'

services: 
  db:
    ports:
      - 5432:5432

  backend:
    ports:
      - 8080:8080

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
        - 8081:8080
    depends_on:
        - db
        