version: '3.4'

services: 
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: todo

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
        - 8081:8080
    depends_on:
        - db

  backend:
    build:
      context: backend/
      target: development
    ports:
      - 8080:8080
    depends_on:
      - db


        