FROM node:16.2-alpine AS frontend-build
WORKDIR /app/src

COPY frontend/ .

RUN npm run build



FROM nginx:mainline-alpine as nginx-base

COPY --from=frontend-build /app/src/build /var/www
COPY nginx.conf /etc/nginx/nginx.conf