version: '3.4'

services: 
  db:
    image: postgres:13.1
    privileged: true
    expose:
      - 5432
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: todo

  backend:
    build:
      context: backend/
      target: development
    expose:
      - 8080
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - backend


        