name: Deploy project on production

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Copy project to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
          source: "./"
          target: "./todo_project"

      - name: Build and deploy the todo project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
          script: |
            cd ./todo_project
            docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build
