name: Check PR style

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Print PR title
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: Check PR title
        if: |
          !startsWith(github.event.pull_request.title, 'Test: ') &&
          !startsWith(github.event.pull_request.title, 'Back: ') &&
          !startsWith(github.event.pull_request.title, 'Front: ')

        run: echo PR title has the wrong format && exit 1
