name: Check PR style

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Print PR title
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: Check PR title
        if: startsWith(github.event.pull_request.title, 'Test')
        run: echo Cool!
